In [80]:
import pandas as pd
from IPython.display import display

In [81]:
df = pd.read_excel('/Users/emilytew/Documents/rwanda/Avocado.xlsx', 'Sheet1')
display(df)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.00,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.00,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.00,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.00,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.00,conventional,2015,Albany
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.00,conventional,2015,Albany
6,2015-11-15,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.00,conventional,2015,Albany
7,2015-11-08,0.98,109428.33,703.75,101815.36,80.00,6829.22,6266.85,562.37,0.00,conventional,2015,Albany
8,2015-11-01,1.02,99811.42,1022.15,87315.57,85.34,11388.36,11104.53,283.83,0.00,conventional,2015,Albany
9,2015-10-25,1.07,74338.76,842.40,64757.44,113.00,8625.92,8061.47,564.45,0.00,conventional,2015,Albany
10,2015-10-18,1.12,84843.44,924.86,75595.85,117.07,8205.66,7877.86,327.80,0.00,conventional,2015,Albany
11,2015-10-11,1.28,64489.17,1582.03,52677.92,105.32,10123.90,9866.27,257.63,0.00,conventional,2015,Albany
12,2015-10-04,1.31,61007.10,2268.32,49880.67,101.36,8756.75,8379.98,376.77,0.00,conventional,2015,Albany
13,2015-09-27,0.99,106803.39,1204.88,99409.21,154.84,6034.46,5888.87,145.59,0.00,conventional,2015,Albany
14,2015-09-20,1.33,69759.01,1028.03,59313.12,150.50,9267.36,8489.10,778.26,0.00,conventional,2015,Albany
15,2015-09-13,1.28,76111.27,985.73,65696.86,142.00,9286.68,8665.19,621.49,0.00,conventional,2015,Albany
16,2015-09-06,1.11,99172.96,879.45,90062.62,240.79,7990.10,7762.87,227.23,0.00,conventional,2015,Albany
17,2015-08-30,1.07,105693.84,689.01,94362.67,335.43,10306.73,10218.93,87.80,0.00,conventional,2015,Albany
18,2015-08-23,1.34,79992.09,733.16,67933.79,444.78,10880.36,10745.79,134.57,0.00,conventional,2015,Albany
19,2015-08-16,1.33,80043.78,539.65,68666.01,394.90,10443.22,10297.68,145.54,0.00,conventional,2015,Albany
20,2015-08-09,1.12,111140.93,584.63,100961.46,368.95,9225.89,9116.34,109.55,0.00,conventional,2015,Albany
21,2015-08-02,1.45,75133.10,509.94,62035.06,741.08,11847.02,11768.52,78.50,0.00,conventional,2015,Albany
22,2015-07-26,1.11,106757.10,648.75,91949.05,966.61,13192.69,13061.53,131.16,0.00,conventional,2015,Albany
23,2015-07-19,1.26,96617.00,1042.10,82049.40,2238.02,11287.48,11103.49,183.99,0.00,conventional,2015,Albany
24,2015-07-12,1.05,124055.31,672.25,94693.52,4257.64,24431.90,24290.08,108.49,33.33,conventional,2015,Albany
25,2015-07-05,1.35,109252.12,869.45,72600.55,5883.16,29898.96,29663.19,235.77,0.00,conventional,2015,Albany
26,2015-06-28,1.37,89534.81,664.23,57545.79,4662.71,26662.08,26311.76,350.32,0.00,conventional,2015,Albany
27,2015-06-21,1.27,104849.39,804.01,76688.55,5481.18,21875.65,21662.00,213.65,0.00,conventional,2015,Albany
28,2015-06-14,1.32,89631.30,850.58,55400.94,4377.19,29002.59,28343.14,659.45,0.00,conventional,2015,Albany
29,2015-06-07,1.07,122743.06,656.71,99220.82,90.32,22775.21,22314.99,460.22,0.00,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219,2018-02-11,1.56,1317000.47,98465.26,270798.27,1839.80,945638.02,768242.42,177144.00,251.60,organic,2018,TotalUS
18220,2018-02-04,1.53,1384683.41,117922.52,287724.61,1703.52,977084.84,774695.74,201878.69,510.41,organic,2018,TotalUS
18221,2018-01-28,1.61,1336979.09,118616.17,280080.34,1270.61,936859.49,796104.27,140652.84,102.38,organic,2018,TotalUS
18222,2018-01-21,1.63,1283987.65,108705.28,259172.13,1490.02,914409.26,710654.40,203526.59,228.27,organic,2018,TotalUS
18223,2018-01-14,1.59,1476651.08,145680.62,323669.83,1580.01,1005593.78,858772.69,146808.97,12.12,organic,2018,TotalUS
18224,2018-01-07,1.51,1517332.70,129541.43,296490.29,1289.07,1089861.24,915452.78,174381.57,26.89,organic,2018,TotalUS
18225,2018-03-25,1.60,271723.08,26996.28,77861.39,117.56,166747.85,87108.00,79495.39,144.46,organic,2018,West
18226,2018-03-18,1.73,210067.47,33437.98,47165.54,110.40,129353.55,73163.12,56020.24,170.19,organic,2018,West
18227,2018-03-11,1.63,264691.87,27566.25,60383.57,276.42,176465.63,107174.93,69290.70,0.00,organic,2018,West
18228,2018-03-04,1.46,347373.17,25990.60,71213.19,79.01,250090.37,85835.17,164087.33,167.87,organic,2018,West
18229,2018-02-25,1.49,301985.61,34200.18,49139.34,85.58,218560.51,99989.62,118314.77,256.12,organic,2018,West
18230,2018-02-18,1.64,224798.60,30149.00,38800.64,123.13,155725.83,120428.13,35257.73,39.97,organic,2018,West
18231,2018-02-11,1.47,275248.53,24732.55,61713.53,243.00,188559.45,88497.05,99810.80,251.60,organic,2018,West
18232,2018-02-04,1.41,283378.47,22474.66,55360.49,133.41,205409.91,70232.59,134666.91,510.41,organic,2018,West
18233,2018-01-28,1.80,185974.53,22918.40,33051.14,93.52,129911.47,77822.23,51986.86,102.38,organic,2018,West
18234,2018-01-21,1.83,189317.99,27049.44,33561.32,439.47,128267.76,76091.99,51947.50,228.27,organic,2018,West
18235,2018-01-14,1.82,207999.67,33869.12,47435.14,433.52,126261.89,89115.78,37133.99,12.12,organic,2018,West
18236,2018-01-07,1.48,297190.60,34734.97,62967.74,157.77,199330.12,103761.55,95544.39,24.18,organic,2018,West
18237,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.00,organic,2018,WestTexNewMexico
18238,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.00,organic,2018,WestTexNewMexico
18239,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.00,organic,2018,WestTexNewMexico
18240,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.00,organic,2018,WestTexNewMexico
18241,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.00,organic,2018,WestTexNewMexico
18242,2018-02-18,1.56,17597.12,1892.05,1928.36,0.00,13776.71,13553.53,223.18,0.00,organic,2018,WestTexNewMexico
18243,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.00,organic,2018,WestTexNewMexico
18244,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.00,organic,2018,WestTexNewMexico
18245,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.00,organic,2018,WestTexNewMexico
18246,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.00,organic,2018,WestTexNewMexico
18247,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.00,organic,2018,WestTexNewMexico
18248,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.00,organic,2018,WestTexNewMexico

In [83]:
df.loc['Total'] = pd.Series(df['AveragePrice'].sum(), index = ['AveragePrice'])
display(df)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27 00:00:00,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.00,conventional,2015.0,Albany
1,2015-12-20 00:00:00,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.00,conventional,2015.0,Albany
2,2015-12-13 00:00:00,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.00,conventional,2015.0,Albany
3,2015-12-06 00:00:00,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.00,conventional,2015.0,Albany
4,2015-11-29 00:00:00,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.00,conventional,2015.0,Albany
5,2015-11-22 00:00:00,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.00,conventional,2015.0,Albany
6,2015-11-15 00:00:00,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.00,conventional,2015.0,Albany
7,2015-11-08 00:00:00,0.98,109428.33,703.75,101815.36,80.00,6829.22,6266.85,562.37,0.00,conventional,2015.0,Albany
8,2015-11-01 00:00:00,1.02,99811.42,1022.15,87315.57,85.34,11388.36,11104.53,283.83,0.00,conventional,2015.0,Albany
9,2015-10-25 00:00:00,1.07,74338.76,842.40,64757.44,113.00,8625.92,8061.47,564.45,0.00,conventional,2015.0,Albany
10,2015-10-18 00:00:00,1.12,84843.44,924.86,75595.85,117.07,8205.66,7877.86,327.80,0.00,conventional,2015.0,Albany
11,2015-10-11 00:00:00,1.28,64489.17,1582.03,52677.92,105.32,10123.90,9866.27,257.63,0.00,conventional,2015.0,Albany
12,2015-10-04 00:00:00,1.31,61007.10,2268.32,49880.67,101.36,8756.75,8379.98,376.77,0.00,conventional,2015.0,Albany
13,2015-09-27 00:00:00,0.99,106803.39,1204.88,99409.21,154.84,6034.46,5888.87,145.59,0.00,conventional,2015.0,Albany
14,2015-09-20 00:00:00,1.33,69759.01,1028.03,59313.12,150.50,9267.36,8489.10,778.26,0.00,conventional,2015.0,Albany
15,2015-09-13 00:00:00,1.28,76111.27,985.73,65696.86,142.00,9286.68,8665.19,621.49,0.00,conventional,2015.0,Albany
16,2015-09-06 00:00:00,1.11,99172.96,879.45,90062.62,240.79,7990.10,7762.87,227.23,0.00,conventional,2015.0,Albany
17,2015-08-30 00:00:00,1.07,105693.84,689.01,94362.67,335.43,10306.73,10218.93,87.80,0.00,conventional,2015.0,Albany
18,2015-08-23 00:00:00,1.34,79992.09,733.16,67933.79,444.78,10880.36,10745.79,134.57,0.00,conventional,2015.0,Albany
19,2015-08-16 00:00:00,1.33,80043.78,539.65,68666.01,394.90,10443.22,10297.68,145.54,0.00,conventional,2015.0,Albany
20,2015-08-09 00:00:00,1.12,111140.93,584.63,100961.46,368.95,9225.89,9116.34,109.55,0.00,conventional,2015.0,Albany
21,2015-08-02 00:00:00,1.45,75133.10,509.94,62035.06,741.08,11847.02,11768.52,78.50,0.00,conventional,2015.0,Albany
22,2015-07-26 00:00:00,1.11,106757.10,648.75,91949.05,966.61,13192.69,13061.53,131.16,0.00,conventional,2015.0,Albany
23,2015-07-19 00:00:00,1.26,96617.00,1042.10,82049.40,2238.02,11287.48,11103.49,183.99,0.00,conventional,2015.0,Albany
24,2015-07-12 00:00:00,1.05,124055.31,672.25,94693.52,4257.64,24431.90,24290.08,108.49,33.33,conventional,2015.0,Albany
25,2015-07-05 00:00:00,1.35,109252.12,869.45,72600.55,5883.16,29898.96,29663.19,235.77,0.00,conventional,2015.0,Albany
26,2015-06-28 00:00:00,1.37,89534.81,664.23,57545.79,4662.71,26662.08,26311.76,350.32,0.00,conventional,2015.0,Albany
27,2015-06-21 00:00:00,1.27,104849.39,804.01,76688.55,5481.18,21875.65,21662.00,213.65,0.00,conventional,2015.0,Albany
28,2015-06-14 00:00:00,1.32,89631.30,850.58,55400.94,4377.19,29002.59,28343.14,659.45,0.00,conventional,2015.0,Albany
29,2015-06-07 00:00:00,1.07,122743.06,656.71,99220.82,90.32,22775.21,22314.99,460.22,0.00,conventional,2015.0,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18220,2018-02-04 00:00:00,1.53,1384683.41,117922.52,287724.61,1703.52,977084.84,774695.74,201878.69,510.41,organic,2018.0,TotalUS
18221,2018-01-28 00:00:00,1.61,1336979.09,118616.17,280080.34,1270.61,936859.49,796104.27,140652.84,102.38,organic,2018.0,TotalUS
18222,2018-01-21 00:00:00,1.63,1283987.65,108705.28,259172.13,1490.02,914409.26,710654.40,203526.59,228.27,organic,2018.0,TotalUS
18223,2018-01-14 00:00:00,1.59,1476651.08,145680.62,323669.83,1580.01,1005593.78,858772.69,146808.97,12.12,organic,2018.0,TotalUS
18224,2018-01-07 00:00:00,1.51,1517332.70,129541.43,296490.29,1289.07,1089861.24,915452.78,174381.57,26.89,organic,2018.0,TotalUS
18225,2018-03-25 00:00:00,1.60,271723.08,26996.28,77861.39,117.56,166747.85,87108.00,79495.39,144.46,organic,2018.0,West
18226,2018-03-18 00:00:00,1.73,210067.47,33437.98,47165.54,110.40,129353.55,73163.12,56020.24,170.19,organic,2018.0,West
18227,2018-03-11 00:00:00,1.63,264691.87,27566.25,60383.57,276.42,176465.63,107174.93,69290.70,0.00,organic,2018.0,West
18228,2018-03-04 00:00:00,1.46,347373.17,25990.60,71213.19,79.01,250090.37,85835.17,164087.33,167.87,organic,2018.0,West
18229,2018-02-25 00:00:00,1.49,301985.61,34200.18,49139.34,85.58,218560.51,99989.62,118314.77,256.12,organic,2018.0,West
18230,2018-02-18 00:00:00,1.64,224798.60,30149.00,38800.64,123.13,155725.83,120428.13,35257.73,39.97,organic,2018.0,West
18231,2018-02-11 00:00:00,1.47,275248.53,24732.55,61713.53,243.00,188559.45,88497.05,99810.80,251.60,organic,2018.0,West
18232,2018-02-04 00:00:00,1.41,283378.47,22474.66,55360.49,133.41,205409.91,70232.59,134666.91,510.41,organic,2018.0,West
18233,2018-01-28 00:00:00,1.80,185974.53,22918.40,33051.14,93.52,129911.47,77822.23,51986.86,102.38,organic,2018.0,West
18234,2018-01-21 00:00:00,1.83,189317.99,27049.44,33561.32,439.47,128267.76,76091.99,51947.50,228.27,organic,2018.0,West
18235,2018-01-14 00:00:00,1.82,207999.67,33869.12,47435.14,433.52,126261.89,89115.78,37133.99,12.12,organic,2018.0,West
18236,2018-01-07 00:00:00,1.48,297190.60,34734.97,62967.74,157.77,199330.12,103761.55,95544.39,24.18,organic,2018.0,West
18237,2018-03-25 00:00:00,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.00,organic,2018.0,WestTexNewMexico
18238,2018-03-18 00:00:00,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.00,organic,2018.0,WestTexNewMexico
18239,2018-03-11 00:00:00,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.00,organic,2018.0,WestTexNewMexico
18240,2018-03-04 00:00:00,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.00,organic,2018.0,WestTexNewMexico
18241,2018-02-25 00:00:00,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.00,organic,2018.0,WestTexNewMexico
18242,2018-02-18 00:00:00,1.56,17597.12,1892.05,1928.36,0.00,13776.71,13553.53,223.18,0.00,organic,2018.0,WestTexNewMexico
18243,2018-02-11 00:00:00,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.00,organic,2018.0,WestTexNewMexico
18244,2018-02-04 00:00:00,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.00,organic,2018.0,WestTexNewMexico
18245,2018-01-28 00:00:00,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.00,organic,2018.0,WestTexNewMexico
18246,2018-01-21 00:00:00,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.00,organic,2018.0,WestTexNewMexico
18247,2018-01-14 00:00:00,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.00,organic,2018.0,WestTexNewMexico
18248,2018-01-07 00:00:00,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.00,organic,2018.0,WestTexNewMexico
Total,NaN,51315.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
# gives sums of the columns
df2 = df.sum(axis=0)
display(df2)

AveragePrice    7.697310e+04
Total Volume    1.552340e+10
4046            5.347111e+09
4225            5.386276e+09
4770            4.168023e+08
Total Bags      4.373176e+09
Small Bags      3.324871e+09
Large Bags      9.916158e+08
XLarge Bags     5.668918e+07
year            3.679268e+07
dtype: float64

In [85]:
# adds those sums onto the bottom of the dataframe

df.loc['sum'] = df[:-1].sum() #This [:-1] means it does not add the 'Total' column we just created above
display(df)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27 00:00:00,1.33,6.423662e+04,1.036740e+03,5.445485e+04,4.816000e+01,8.696870e+03,8.603620e+03,9.325000e+01,0.00,conventional,2015.0,Albany
1,2015-12-20 00:00:00,1.35,5.487698e+04,6.742800e+02,4.463881e+04,5.833000e+01,9.505560e+03,9.408070e+03,9.749000e+01,0.00,conventional,2015.0,Albany
2,2015-12-13 00:00:00,0.93,1.182202e+05,7.947000e+02,1.091497e+05,1.305000e+02,8.145350e+03,8.042210e+03,1.031400e+02,0.00,conventional,2015.0,Albany
3,2015-12-06 00:00:00,1.08,7.899215e+04,1.132000e+03,7.197641e+04,7.258000e+01,5.811160e+03,5.677400e+03,1.337600e+02,0.00,conventional,2015.0,Albany
4,2015-11-29 00:00:00,1.28,5.103960e+04,9.414800e+02,4.383839e+04,7.578000e+01,6.183950e+03,5.986260e+03,1.976900e+02,0.00,conventional,2015.0,Albany
5,2015-11-22 00:00:00,1.26,5.597978e+04,1.184270e+03,4.806799e+04,4.361000e+01,6.683910e+03,6.556470e+03,1.274400e+02,0.00,conventional,2015.0,Albany
6,2015-11-15 00:00:00,0.99,8.345376e+04,1.368920e+03,7.367272e+04,9.326000e+01,8.318860e+03,8.196810e+03,1.220500e+02,0.00,conventional,2015.0,Albany
7,2015-11-08 00:00:00,0.98,1.094283e+05,7.037500e+02,1.018154e+05,8.000000e+01,6.829220e+03,6.266850e+03,5.623700e+02,0.00,conventional,2015.0,Albany
8,2015-11-01 00:00:00,1.02,9.981142e+04,1.022150e+03,8.731557e+04,8.534000e+01,1.138836e+04,1.110453e+04,2.838300e+02,0.00,conventional,2015.0,Albany
9,2015-10-25 00:00:00,1.07,7.433876e+04,8.424000e+02,6.475744e+04,1.130000e+02,8.625920e+03,8.061470e+03,5.644500e+02,0.00,conventional,2015.0,Albany
10,2015-10-18 00:00:00,1.12,8.484344e+04,9.248600e+02,7.559585e+04,1.170700e+02,8.205660e+03,7.877860e+03,3.278000e+02,0.00,conventional,2015.0,Albany
11,2015-10-11 00:00:00,1.28,6.448917e+04,1.582030e+03,5.267792e+04,1.053200e+02,1.012390e+04,9.866270e+03,2.576300e+02,0.00,conventional,2015.0,Albany
12,2015-10-04 00:00:00,1.31,6.100710e+04,2.268320e+03,4.988067e+04,1.013600e+02,8.756750e+03,8.379980e+03,3.767700e+02,0.00,conventional,2015.0,Albany
13,2015-09-27 00:00:00,0.99,1.068034e+05,1.204880e+03,9.940921e+04,1.548400e+02,6.034460e+03,5.888870e+03,1.455900e+02,0.00,conventional,2015.0,Albany
14,2015-09-20 00:00:00,1.33,6.975901e+04,1.028030e+03,5.931312e+04,1.505000e+02,9.267360e+03,8.489100e+03,7.782600e+02,0.00,conventional,2015.0,Albany
15,2015-09-13 00:00:00,1.28,7.611127e+04,9.857300e+02,6.569686e+04,1.420000e+02,9.286680e+03,8.665190e+03,6.214900e+02,0.00,conventional,2015.0,Albany
16,2015-09-06 00:00:00,1.11,9.917296e+04,8.794500e+02,9.006262e+04,2.407900e+02,7.990100e+03,7.762870e+03,2.272300e+02,0.00,conventional,2015.0,Albany
17,2015-08-30 00:00:00,1.07,1.056938e+05,6.890100e+02,9.436267e+04,3.354300e+02,1.030673e+04,1.021893e+04,8.780000e+01,0.00,conventional,2015.0,Albany
18,2015-08-23 00:00:00,1.34,7.999209e+04,7.331600e+02,6.793379e+04,4.447800e+02,1.088036e+04,1.074579e+04,1.345700e+02,0.00,conventional,2015.0,Albany
19,2015-08-16 00:00:00,1.33,8.004378e+04,5.396500e+02,6.866601e+04,3.949000e+02,1.044322e+04,1.029768e+04,1.455400e+02,0.00,conventional,2015.0,Albany
20,2015-08-09 00:00:00,1.12,1.111409e+05,5.846300e+02,1.009615e+05,3.689500e+02,9.225890e+03,9.116340e+03,1.095500e+02,0.00,conventional,2015.0,Albany
21,2015-08-02 00:00:00,1.45,7.513310e+04,5.099400e+02,6.203506e+04,7.410800e+02,1.184702e+04,1.176852e+04,7.850000e+01,0.00,conventional,2015.0,Albany
22,2015-07-26 00:00:00,1.11,1.067571e+05,6.487500e+02,9.194905e+04,9.666100e+02,1.319269e+04,1.306153e+04,1.311600e+02,0.00,conventional,2015.0,Albany
23,2015-07-19 00:00:00,1.26,9.661700e+04,1.042100e+03,8.204940e+04,2.238020e+03,1.128748e+04,1.110349e+04,1.839900e+02,0.00,conventional,2015.0,Albany
24,2015-07-12 00:00:00,1.05,1.240553e+05,6.722500e+02,9.469352e+04,4.257640e+03,2.443190e+04,2.429008e+04,1.084900e+02,33.33,conventional,2015.0,Albany
25,2015-07-05 00:00:00,1.35,1.092521e+05,8.694500e+02,7.260055e+04,5.883160e+03,2.989896e+04,2.966319e+04,2.357700e+02,0.00,conventional,2015.0,Albany
26,2015-06-28 00:00:00,1.37,8.953481e+04,6.642300e+02,5.754579e+04,4.662710e+03,2.666208e+04,2.631176e+04,3.503200e+02,0.00,conventional,2015.0,Albany
27,2015-06-21 00:00:00,1.27,1.048494e+05,8.040100e+02,7.668855e+04,5.481180e+03,2.187565e+04,2.166200e+04,2.136500e+02,0.00,conventional,2015.0,Albany
28,2015-06-14 00:00:00,1.32,8.963130e+04,8.505800e+02,5.540094e+04,4.377190e+03,2.900259e+04,2.834314e+04,6.594500e+02,0.00,conventional,2015.0,Albany
29,2015-06-07 00:00:00,1.07,1.227431e+05,6.567100e+02,9.922082e+04,9.032000e+01,2.277521e+04,2.231499e+04,4.602200e+02,0.00,conventional,2015.0,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18221,2018-01-28 00:00:00,1.61,1.336979e+06,1.186162e+05,2.800803e+05,1.270610e+03,9.368595e+05,7.961043e+05,1.406528e+05,102.38,organic,2018.0,TotalUS
18222,2018-01-21 00:00:00,1.63,1.283988e+06,1.087053e+05,2.591721e+05,1.490020e+03,9.144093e+05,7.106544e+05,2.035266e+05,228.27,organic,2018.0,TotalUS
18223,2018-01-14 00:00:00,1.59,1.476651e+06,1.456806e+05,3.236698e+05,1.580010e+03,1.005594e+06,8.587727e+05,1.468090e+05,12.12,organic,2018.0,TotalUS
18224,2018-01-07 00:00:00,1.51,1.517333e+06,1.295414e+05,2.964903e+05,1.289070e+03,1.089861e+06,9.154528e+05,1.743816e+05,26.89,organic,2018.0,TotalUS
18225,2018-03-25 00:00:00,1.60,2.717231e+05,2.699628e+04,7.786139e+04,1.175600e+02,1.667479e+05,8.710800e+04,7.949539e+04,144.46,organic,2018.0,West
18226,2018-03-18 00:00:00,1.73,2.100675e+05,3.343798e+04,4.716554e+04,1.104000e+02,1.293536e+05,7.316312e+04,5.602024e+04,170.19,organic,2018.0,West
18227,2018-03-11 00:00:00,1.63,2.646919e+05,2.756625e+04,6.038357e+04,2.764200e+02,1.764656e+05,1.071749e+05,6.929070e+04,0.00,organic,2018.0,West
18228,2018-03-04 00:00:00,1.46,3.473732e+05,2.599060e+04,7.121319e+04,7.901000e+01,2.500904e+05,8.583517e+04,1.640873e+05,167.87,organic,2018.0,West
18229,2018-02-25 00:00:00,1.49,3.019856e+05,3.420018e+04,4.913934e+04,8.558000e+01,2.185605e+05,9.998962e+04,1.183148e+05,256.12,organic,2018.0,West
18230,2018-02-18 00:00:00,1.64,2.247986e+05,3.014900e+04,3.880064e+04,1.231300e+02,1.557258e+05,1.204281e+05,3.525773e+04,39.97,organic,2018.0,West
18231,2018-02-11 00:00:00,1.47,2.752485e+05,2.473255e+04,6.171353e+04,2.430000e+02,1.885595e+05,8.849705e+04,9.981080e+04,251.60,organic,2018.0,West
18232,2018-02-04 00:00:00,1.41,2.833785e+05,2.247466e+04,5.536049e+04,1.334100e+02,2.054099e+05,7.023259e+04,1.346669e+05,510.41,organic,2018.0,West
18233,2018-01-28 00:00:00,1.80,1.859745e+05,2.291840e+04,3.305114e+04,9.352000e+01,1.299115e+05,7.782223e+04,5.198686e+04,102.38,organic,2018.0,West
18234,2018-01-21 00:00:00,1.83,1.893180e+05,2.704944e+04,3.356132e+04,4.394700e+02,1.282678e+05,7.609199e+04,5.194750e+04,228.27,organic,2018.0,West
18235,2018-01-14 00:00:00,1.82,2.079997e+05,3.386912e+04,4.743514e+04,4.335200e+02,1.262619e+05,8.911578e+04,3.713399e+04,12.12,organic,2018.0,West
18236,2018-01-07 00:00:00,1.48,2.971906e+05,3.473497e+04,6.296774e+04,1.577700e+02,1.993301e+05,1.037616e+05,9.554439e+04,24.18,organic,2018.0,West
18237,2018-03-25 00:00:00,1.62,1.530340e+04,2.325300e+03,2.171660e+03,0.000000e+00,1.080644e+04,1.056980e+04,2.366400e+02,0.00,organic,2018.0,WestTexNewMexico
18238,2018-03-18 00:00:00,1.56,1.589638e+04,2.055350e+03,1.499550e+03,0.000000e+00,1.234148e+04,1.211481e+04,2.266700e+02,0.00,organic,2018.0,WestTexNewMexico
18239,2018-03-11 00:00:00,1.56,2.212842e+04,2.162670e+03,3.194250e+03,8.930000e+00,1.676257e+04,1.651032e+04,2.522500e+02,0.00,organic,2018.0,WestTexNewMexico
18240,2018-03-04 00:00:00,1.54,1.739330e+04,1.832240e+03,1.905570e+03,0.000000e+00,1.365549e+04,1.340193e+04,2.535600e+02,0.00,organic,2018.0,WestTexNewMexico
18241,2018-02-25 00:00:00,1.57,1.842124e+04,1.974260e+03,2.482650e+03,0.000000e+00,1.396433e+04,1.369827e+04,2.660600e+02,0.00,organic,2018.0,WestTexNewMexico
18242,2018-02-18 00:00:00,1.56,1.759712e+04,1.892050e+03,1.928360e+03,0.000000e+00,1.377671e+04,1.355353e+04,2.231800e+02,0.00,organic,2018.0,WestTexNewMexico
18243,2018-02-11 00:00:00,1.57,1.598617e+04,1.924280e+03,1.368320e+03,0.000000e+00,1.269357e+04,1.243735e+04,2.562200e+02,0.00,organic,2018.0,WestTexNewMexico
18244,2018-02-04 00:00:00,1.63,1.707483e+04,2.046960e+03,1.529200e+03,0.000000e+00,1.349867e+04,1.306682e+04,4.318500e+02,0.00,organic,2018.0,WestTexNewMexico
18245,2018-01-28 00:00:00,1.71,1.388804e+04,1.191700e+03,3.431500e+03,0.000000e+00,9.264840e+03,8.940040e+03,3.248000e+02,0.00,organic,2018.0,WestTexNewMexico
18246,2018-01-21 00:00:00,1.87,1.376676e+04,1.191920e+03,2.452790e+03,7.279400e+02,9.394110e+03,9.351800e+03,4.231000e+01,0.00,organic,2018.0,WestTexNewMexico
18247,2018-01-14 00:00:00,1.93,1.620522e+04,1.527630e+03,2.981040e+03,7.270100e+02,1.096954e+04,1.091954e+04,5.000000e+01,0.00,organic,2018.0,WestTexNewMexico
18248,2018-01-07 00:00:00,1.62,1.748958e+04,2.894770e+03,2.356130e+03,2.245300e+02,1.201415e+04,1.198814e+04,2.601000e+01,0.00,organic,2018.0,WestTexNewMexico
Total,NaN,51315.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sum,NaN,25657.70,1.552340e+10,5.347111e+09,5.386276e+09,4.168023e+08,4.373176e+09,3.324871e+09,9.916158e+08,56689177.33,NaN,36792683.0,NaN

### Saving the dataframes

In [86]:
import pickle

In [87]:
df.to_pickle('/Users/emilytew/Documents/rwanda/Avocado_changed.pkl')

In [88]:
df = pd.read_pickle('/Users/emilytew/Documents/rwanda/Avocado_changed.pkl')

In [89]:
display(df)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27 00:00:00,1.33,6.423662e+04,1.036740e+03,5.445485e+04,4.816000e+01,8.696870e+03,8.603620e+03,9.325000e+01,0.00,conventional,2015.0,Albany
1,2015-12-20 00:00:00,1.35,5.487698e+04,6.742800e+02,4.463881e+04,5.833000e+01,9.505560e+03,9.408070e+03,9.749000e+01,0.00,conventional,2015.0,Albany
2,2015-12-13 00:00:00,0.93,1.182202e+05,7.947000e+02,1.091497e+05,1.305000e+02,8.145350e+03,8.042210e+03,1.031400e+02,0.00,conventional,2015.0,Albany
3,2015-12-06 00:00:00,1.08,7.899215e+04,1.132000e+03,7.197641e+04,7.258000e+01,5.811160e+03,5.677400e+03,1.337600e+02,0.00,conventional,2015.0,Albany
4,2015-11-29 00:00:00,1.28,5.103960e+04,9.414800e+02,4.383839e+04,7.578000e+01,6.183950e+03,5.986260e+03,1.976900e+02,0.00,conventional,2015.0,Albany
5,2015-11-22 00:00:00,1.26,5.597978e+04,1.184270e+03,4.806799e+04,4.361000e+01,6.683910e+03,6.556470e+03,1.274400e+02,0.00,conventional,2015.0,Albany
6,2015-11-15 00:00:00,0.99,8.345376e+04,1.368920e+03,7.367272e+04,9.326000e+01,8.318860e+03,8.196810e+03,1.220500e+02,0.00,conventional,2015.0,Albany
7,2015-11-08 00:00:00,0.98,1.094283e+05,7.037500e+02,1.018154e+05,8.000000e+01,6.829220e+03,6.266850e+03,5.623700e+02,0.00,conventional,2015.0,Albany
8,2015-11-01 00:00:00,1.02,9.981142e+04,1.022150e+03,8.731557e+04,8.534000e+01,1.138836e+04,1.110453e+04,2.838300e+02,0.00,conventional,2015.0,Albany
9,2015-10-25 00:00:00,1.07,7.433876e+04,8.424000e+02,6.475744e+04,1.130000e+02,8.625920e+03,8.061470e+03,5.644500e+02,0.00,conventional,2015.0,Albany
10,2015-10-18 00:00:00,1.12,8.484344e+04,9.248600e+02,7.559585e+04,1.170700e+02,8.205660e+03,7.877860e+03,3.278000e+02,0.00,conventional,2015.0,Albany
11,2015-10-11 00:00:00,1.28,6.448917e+04,1.582030e+03,5.267792e+04,1.053200e+02,1.012390e+04,9.866270e+03,2.576300e+02,0.00,conventional,2015.0,Albany
12,2015-10-04 00:00:00,1.31,6.100710e+04,2.268320e+03,4.988067e+04,1.013600e+02,8.756750e+03,8.379980e+03,3.767700e+02,0.00,conventional,2015.0,Albany
13,2015-09-27 00:00:00,0.99,1.068034e+05,1.204880e+03,9.940921e+04,1.548400e+02,6.034460e+03,5.888870e+03,1.455900e+02,0.00,conventional,2015.0,Albany
14,2015-09-20 00:00:00,1.33,6.975901e+04,1.028030e+03,5.931312e+04,1.505000e+02,9.267360e+03,8.489100e+03,7.782600e+02,0.00,conventional,2015.0,Albany
15,2015-09-13 00:00:00,1.28,7.611127e+04,9.857300e+02,6.569686e+04,1.420000e+02,9.286680e+03,8.665190e+03,6.214900e+02,0.00,conventional,2015.0,Albany
16,2015-09-06 00:00:00,1.11,9.917296e+04,8.794500e+02,9.006262e+04,2.407900e+02,7.990100e+03,7.762870e+03,2.272300e+02,0.00,conventional,2015.0,Albany
17,2015-08-30 00:00:00,1.07,1.056938e+05,6.890100e+02,9.436267e+04,3.354300e+02,1.030673e+04,1.021893e+04,8.780000e+01,0.00,conventional,2015.0,Albany
18,2015-08-23 00:00:00,1.34,7.999209e+04,7.331600e+02,6.793379e+04,4.447800e+02,1.088036e+04,1.074579e+04,1.345700e+02,0.00,conventional,2015.0,Albany
19,2015-08-16 00:00:00,1.33,8.004378e+04,5.396500e+02,6.866601e+04,3.949000e+02,1.044322e+04,1.029768e+04,1.455400e+02,0.00,conventional,2015.0,Albany
20,2015-08-09 00:00:00,1.12,1.111409e+05,5.846300e+02,1.009615e+05,3.689500e+02,9.225890e+03,9.116340e+03,1.095500e+02,0.00,conventional,2015.0,Albany
21,2015-08-02 00:00:00,1.45,7.513310e+04,5.099400e+02,6.203506e+04,7.410800e+02,1.184702e+04,1.176852e+04,7.850000e+01,0.00,conventional,2015.0,Albany
22,2015-07-26 00:00:00,1.11,1.067571e+05,6.487500e+02,9.194905e+04,9.666100e+02,1.319269e+04,1.306153e+04,1.311600e+02,0.00,conventional,2015.0,Albany
23,2015-07-19 00:00:00,1.26,9.661700e+04,1.042100e+03,8.204940e+04,2.238020e+03,1.128748e+04,1.110349e+04,1.839900e+02,0.00,conventional,2015.0,Albany
24,2015-07-12 00:00:00,1.05,1.240553e+05,6.722500e+02,9.469352e+04,4.257640e+03,2.443190e+04,2.429008e+04,1.084900e+02,33.33,conventional,2015.0,Albany
25,2015-07-05 00:00:00,1.35,1.092521e+05,8.694500e+02,7.260055e+04,5.883160e+03,2.989896e+04,2.966319e+04,2.357700e+02,0.00,conventional,2015.0,Albany
26,2015-06-28 00:00:00,1.37,8.953481e+04,6.642300e+02,5.754579e+04,4.662710e+03,2.666208e+04,2.631176e+04,3.503200e+02,0.00,conventional,2015.0,Albany
27,2015-06-21 00:00:00,1.27,1.048494e+05,8.040100e+02,7.668855e+04,5.481180e+03,2.187565e+04,2.166200e+04,2.136500e+02,0.00,conventional,2015.0,Albany
28,2015-06-14 00:00:00,1.32,8.963130e+04,8.505800e+02,5.540094e+04,4.377190e+03,2.900259e+04,2.834314e+04,6.594500e+02,0.00,conventional,2015.0,Albany
29,2015-06-07 00:00:00,1.07,1.227431e+05,6.567100e+02,9.922082e+04,9.032000e+01,2.277521e+04,2.231499e+04,4.602200e+02,0.00,conventional,2015.0,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18221,2018-01-28 00:00:00,1.61,1.336979e+06,1.186162e+05,2.800803e+05,1.270610e+03,9.368595e+05,7.961043e+05,1.406528e+05,102.38,organic,2018.0,TotalUS
18222,2018-01-21 00:00:00,1.63,1.283988e+06,1.087053e+05,2.591721e+05,1.490020e+03,9.144093e+05,7.106544e+05,2.035266e+05,228.27,organic,2018.0,TotalUS
18223,2018-01-14 00:00:00,1.59,1.476651e+06,1.456806e+05,3.236698e+05,1.580010e+03,1.005594e+06,8.587727e+05,1.468090e+05,12.12,organic,2018.0,TotalUS
18224,2018-01-07 00:00:00,1.51,1.517333e+06,1.295414e+05,2.964903e+05,1.289070e+03,1.089861e+06,9.154528e+05,1.743816e+05,26.89,organic,2018.0,TotalUS
18225,2018-03-25 00:00:00,1.60,2.717231e+05,2.699628e+04,7.786139e+04,1.175600e+02,1.667479e+05,8.710800e+04,7.949539e+04,144.46,organic,2018.0,West
18226,2018-03-18 00:00:00,1.73,2.100675e+05,3.343798e+04,4.716554e+04,1.104000e+02,1.293536e+05,7.316312e+04,5.602024e+04,170.19,organic,2018.0,West
18227,2018-03-11 00:00:00,1.63,2.646919e+05,2.756625e+04,6.038357e+04,2.764200e+02,1.764656e+05,1.071749e+05,6.929070e+04,0.00,organic,2018.0,West
18228,2018-03-04 00:00:00,1.46,3.473732e+05,2.599060e+04,7.121319e+04,7.901000e+01,2.500904e+05,8.583517e+04,1.640873e+05,167.87,organic,2018.0,West
18229,2018-02-25 00:00:00,1.49,3.019856e+05,3.420018e+04,4.913934e+04,8.558000e+01,2.185605e+05,9.998962e+04,1.183148e+05,256.12,organic,2018.0,West
18230,2018-02-18 00:00:00,1.64,2.247986e+05,3.014900e+04,3.880064e+04,1.231300e+02,1.557258e+05,1.204281e+05,3.525773e+04,39.97,organic,2018.0,West
18231,2018-02-11 00:00:00,1.47,2.752485e+05,2.473255e+04,6.171353e+04,2.430000e+02,1.885595e+05,8.849705e+04,9.981080e+04,251.60,organic,2018.0,West
18232,2018-02-04 00:00:00,1.41,2.833785e+05,2.247466e+04,5.536049e+04,1.334100e+02,2.054099e+05,7.023259e+04,1.346669e+05,510.41,organic,2018.0,West
18233,2018-01-28 00:00:00,1.80,1.859745e+05,2.291840e+04,3.305114e+04,9.352000e+01,1.299115e+05,7.782223e+04,5.198686e+04,102.38,organic,2018.0,West
18234,2018-01-21 00:00:00,1.83,1.893180e+05,2.704944e+04,3.356132e+04,4.394700e+02,1.282678e+05,7.609199e+04,5.194750e+04,228.27,organic,2018.0,West
18235,2018-01-14 00:00:00,1.82,2.079997e+05,3.386912e+04,4.743514e+04,4.335200e+02,1.262619e+05,8.911578e+04,3.713399e+04,12.12,organic,2018.0,West
18236,2018-01-07 00:00:00,1.48,2.971906e+05,3.473497e+04,6.296774e+04,1.577700e+02,1.993301e+05,1.037616e+05,9.554439e+04,24.18,organic,2018.0,West
18237,2018-03-25 00:00:00,1.62,1.530340e+04,2.325300e+03,2.171660e+03,0.000000e+00,1.080644e+04,1.056980e+04,2.366400e+02,0.00,organic,2018.0,WestTexNewMexico
18238,2018-03-18 00:00:00,1.56,1.589638e+04,2.055350e+03,1.499550e+03,0.000000e+00,1.234148e+04,1.211481e+04,2.266700e+02,0.00,organic,2018.0,WestTexNewMexico
18239,2018-03-11 00:00:00,1.56,2.212842e+04,2.162670e+03,3.194250e+03,8.930000e+00,1.676257e+04,1.651032e+04,2.522500e+02,0.00,organic,2018.0,WestTexNewMexico
18240,2018-03-04 00:00:00,1.54,1.739330e+04,1.832240e+03,1.905570e+03,0.000000e+00,1.365549e+04,1.340193e+04,2.535600e+02,0.00,organic,2018.0,WestTexNewMexico
18241,2018-02-25 00:00:00,1.57,1.842124e+04,1.974260e+03,2.482650e+03,0.000000e+00,1.396433e+04,1.369827e+04,2.660600e+02,0.00,organic,2018.0,WestTexNewMexico
18242,2018-02-18 00:00:00,1.56,1.759712e+04,1.892050e+03,1.928360e+03,0.000000e+00,1.377671e+04,1.355353e+04,2.231800e+02,0.00,organic,2018.0,WestTexNewMexico
18243,2018-02-11 00:00:00,1.57,1.598617e+04,1.924280e+03,1.368320e+03,0.000000e+00,1.269357e+04,1.243735e+04,2.562200e+02,0.00,organic,2018.0,WestTexNewMexico
18244,2018-02-04 00:00:00,1.63,1.707483e+04,2.046960e+03,1.529200e+03,0.000000e+00,1.349867e+04,1.306682e+04,4.318500e+02,0.00,organic,2018.0,WestTexNewMexico
18245,2018-01-28 00:00:00,1.71,1.388804e+04,1.191700e+03,3.431500e+03,0.000000e+00,9.264840e+03,8.940040e+03,3.248000e+02,0.00,organic,2018.0,WestTexNewMexico
18246,2018-01-21 00:00:00,1.87,1.376676e+04,1.191920e+03,2.452790e+03,7.279400e+02,9.394110e+03,9.351800e+03,4.231000e+01,0.00,organic,2018.0,WestTexNewMexico
18247,2018-01-14 00:00:00,1.93,1.620522e+04,1.527630e+03,2.981040e+03,7.270100e+02,1.096954e+04,1.091954e+04,5.000000e+01,0.00,organic,2018.0,WestTexNewMexico
18248,2018-01-07 00:00:00,1.62,1.748958e+04,2.894770e+03,2.356130e+03,2.245300e+02,1.201415e+04,1.198814e+04,2.601000e+01,0.00,organic,2018.0,WestTexNewMexico
Total,NaN,51315.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sum,NaN,25657.70,1.552340e+10,5.347111e+09,5.386276e+09,4.168023e+08,4.373176e+09,3.324871e+09,9.916158e+08,56689177.33,NaN,36792683.0,NaN

### Referring to a cell

In [93]:
df.loc['Total']['AveragePrice']

51315.399999999994

In [94]:
df.iloc[18248]['AveragePrice']

1.62

In [97]:
# Multiplication
Multiplication = df.loc['Total']['AveragePrice'] * df.iloc[18248]['AveragePrice']
print(Multiplication)

83130.94799999999

In [98]:
# Addition
Addition = df.loc['Total']['AveragePrice'] + df.iloc[18248]['AveragePrice']
print(Addition)

51317.02